<a href="https://colab.research.google.com/github/vadhan123/NLP/blob/main/NLP_lab_15_22266_ELMO_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ELMO BANK

# IMPORT LIBRARIES

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np

# LOAD ELMO MODEL

In [2]:
elmo = hub.load("https://tfhub.dev/google/elmo/3")

# TEXT CORPUS

In [3]:
sentences=["The bank will not approve the loan",
           "He sat on the river bank"]

# GENERATE EMBEDDINGS

In [4]:
embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']
print(embeddings.shape)

(2, 7, 1024)


# INSPECT WORD EMBEDDING("BANK

In [5]:
tokenized = [sentence.split() for sentence in sentences]
indx1 = tokenized[0].index('bank')
indx2= tokenized[1].index("bank")
bank_emb_1= embeddings[0][indx1]
bank_emb_2= embeddings[1][indx2]
print("First 10 values (sentennce 1):",bank_emb_1[:10])
print("First 10 values (sentennce 2):",bank_emb_2[:10])

First 10 values (sentennce 1): tf.Tensor(
[-0.9086765  -0.36578754 -0.07339765  0.586675    0.22132948 -0.7657321
 -0.11816446 -0.30227882 -0.06137528  0.1695182 ], shape=(10,), dtype=float32)
First 10 values (sentennce 2): tf.Tensor(
[-0.15614763  0.28345656 -0.08914638  0.2069506   0.1524184  -0.2037305
 -0.10812807  0.03747292  0.5214868   0.35352594], shape=(10,), dtype=float32)


# compare context (cosine similarity)

In [6]:
def cosine_similaity(a,b):
  return np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))
sim = cosine_similaity(bank_emb_1,bank_emb_2.numpy())
print("Similarity between 'bank' meaning:", sim)

Similarity between 'bank' meaning: 0.57813895


# ELMO BAT

# TEXT CORPUS

In [7]:
text=[
    "The bat iss flying",
    "He hit the ball with a bat"
]

# GENERATE EMBEDDINGS

In [8]:
embedding = elmo.signatures['default'](tf.constant(text))['elmo']
print(embedding.shape)

(2, 7, 1024)


# INSPECT WORD EMBEDDING ("BAT")

In [9]:
tokenized = [sentences.split() for sentences in text]
idx1=tokenized[0].index("bat")
idx2=tokenized[1].index("bat")
bat_emb_1=embedding[0][idx1]
bat_emb_2=embedding[1][idx2]
print("First 10 values (sentence 1):",bat_emb_1[:10])
print("First 10 values (sentence 2):",bat_emb_2[:10])

First 10 values (sentence 1): tf.Tensor(
[-0.45903727 -0.27516434 -0.26348162 -0.12380227 -0.11530864 -0.45880768
 -0.12675564 -0.12455821 -0.2630463  -0.1839562 ], shape=(10,), dtype=float32)
First 10 values (sentence 2): tf.Tensor(
[-0.20741455  0.01774421  0.12503807 -0.28234187 -0.23928387  0.04694621
 -0.08645728  0.31607887 -0.13618736 -0.05437148], shape=(10,), dtype=float32)


# comapare context (cosine similarity)

In [10]:
def cosine_similarity(A,B):
  return np.dot(A,B)/(np.linalog.norm(A)*np.linalg.norm(B))
simi = cosine_similaity(bat_emb_1.numpy(),bat_emb_2.numpy())
print("Similarity between 'bat' meanings:",simi)


Similarity between 'bat' meanings: 0.6627627


# BERT MODEL BANK

In [11]:
sent=[
    "The bank will not approve the loan",
    "He sat on the river bank"
]


In [12]:
preprocess= hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_model = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3")

# PREPROCESS INPUT

In [13]:
input=preprocess(sent)
print(input.keys())

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])


# GENERATE EMBEDDINGS

In [14]:
outputs=bert_model(input)
embeddings=outputs['sequence_output']
print("Embedding shape: ",embeddings.shape)

Embedding shape:  (2, 128, 768)


EXREACT BANK EMBEDDINGS

In [15]:
at_emb_1 = embeddings[0][2]
bat_emb_2 = embeddings[1][6]
print("First 10 values (Sentence 1):", bat_emb_1[:10])
print("First 10 values (Sentence 2):", bat_emb_2[:10])

First 10 values (Sentence 1): tf.Tensor(
[-0.45903727 -0.27516434 -0.26348162 -0.12380227 -0.11530864 -0.45880768
 -0.12675564 -0.12455821 -0.2630463  -0.1839562 ], shape=(10,), dtype=float32)
First 10 values (Sentence 2): tf.Tensor(
[-0.54906416 -0.6723894  -0.70398474  0.00643284 -0.5798309   0.31554195
  0.22425319  0.8700537  -0.11308742 -0.9146495 ], shape=(10,), dtype=float32)


# Get Tokens

In [16]:
tokenizer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokens=preprocess(sent)['input_word_ids']
print(tokens)

tf.Tensor(
[[  101  1996  2924  2097  2025 14300  1996  5414   102     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [  101  2002  2938  2006  1996  2314  2924   102     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0 

# COSINE SIMILARITY

In [17]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

sim = cosine_similarity(bank_emb_1.numpy(), bank_emb_2.numpy())

print("Similarity between 'bank' meanings:", sim)

Similarity between 'bank' meanings: 0.57813895


# BERT BAT

In [18]:
sentences = [
    "The bat is flying",
    "He hit the ball with a bat"
]

# PREPROCESS INPUT

In [19]:
inputs = preprocess(sentences)
print(inputs.keys())

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])


# GENERATE EMBEDDINGS

In [20]:
outputs = bert_model(inputs)
embeddings = outputs['sequence_output']
print("Embedding shape:", embeddings.shape)

Embedding shape: (2, 128, 768)


# GET TOKENS

In [21]:
tokenizer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokens = preprocess(sentences)['input_word_ids']

print(tokens)

tf.Tensor(
[[ 101 1996 7151 2003 3909  102    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 101 2002 2718 1996 3608 2007 1037 7151  102    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    

EXTRACT BAT EMBEDDINGS

In [22]:
bat_emb_1 = embeddings[0][2]
bat_emb_2 = embeddings[1][7]
print("First 10 values (Sentence 1):", bat_emb_1[:10])
print("First 10 values (Sentence 2):", bat_emb_2[:10])

First 10 values (Sentence 1): tf.Tensor(
[-6.0895458e-05  2.6044571e-01  1.2677926e-01 -2.8091672e-01
  1.3292238e-02 -4.8430103e-01  7.0899075e-01  7.3061740e-01
  2.0883048e-01 -7.8647310e-01], shape=(10,), dtype=float32)
First 10 values (Sentence 2): tf.Tensor(
[-0.06056872 -0.90724915 -0.06744897 -0.27453673 -0.4663377   0.04165859
  0.23526248  0.35729024  0.9171281  -0.67234385], shape=(10,), dtype=float32)


# COSINE SIMPILARITY

In [23]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

sim = cosine_similarity(bat_emb_1.numpy(), bat_emb_2.numpy())

print("Similarity between 'bat' meanings:", sim)

Similarity between 'bat' meanings: 0.4342774


# TEXT CLASSIFICATION USING ELMO + NAVIVE BAYES

# IMPORT LIBRARIES

In [24]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# TEXT

In [25]:
sentences =[
    "Win money now",
    "Claim your prize",
    "Hello how are you",
    "Let's meet tomorrow",
    "Free lottery ticket",
    "Are you coming today"
]
labels = [1,1,0,0,1,0]

# LOAD ELMO MODEL

In [28]:
elmo = hub.load('https://tfhub.dev/google/elmo/3')

# GENERATE ELMO EMBEDDINGS

In [31]:
embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']
print("Shape:", embeddings.shape)

Shape: (6, 4, 1024)


# Convert to Sentence Embeddings

In [32]:
sentence_embeddings=tf.reduce_mean(embeddings, axis=1)
x= sentence_embeddings.numpy()
y=np.array(labels)
print("Features shape:", x.shape)

Features shape: (6, 1024)


# TRAIN-TEST SPLIT

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

TRAIN MODEL

In [39]:
model= GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

MODEL TESTING

In [41]:
y_pred = model.predict(X_test)
print("Predictions: ", y_pred)
print("Actual: ", y_test)

Predictions:  [0 0]
Actual:  [1 1]


MODEL-EVALUATION

In [42]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.0


# PREDICTION ON NEW TEXT

In [43]:
new_sentence = ["Congratulations! You won a free ticket"]

new_emb = elmo.signatures['default'](tf.constant(new_sentence))['elmo']
new_emb = tf.reduce_mean(new_emb, axis=1)

prediction = model.predict(new_emb.numpy())

print("Prediction:", "Spam" if prediction[0] == 1 else "Not Spam")


Prediction: Not Spam


#TEXT CLASSIFICATION USING BERT + NAVIVE BAYES


In [44]:
preprocess=hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_model = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3")

In [45]:
bert_inputs = preprocess(sentences)


In [46]:
bert_outputs=bert_model(bert_inputs)
bert_features=bert_outputs['pooled_output'].numpy()


In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    bert_features, labels, test_size=0.2, random_state=42
)

nb_bert = GaussianNB()
nb_bert.fit(X_train, y_train)

y_pred_bert = nb_bert.predict(X_test)
acc_bert = accuracy_score(y_test, y_pred_bert)

print("BERT Accuracy:", acc_bert)


BERT Accuracy: 0.0
